name: Deploy

on:
  workflow_dispatch  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dashboard code
      uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: pnpm
    - name: Install package and build
      run: |
        pnpm install
        pnpm build
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: dist
        filename: 'release.zip'

    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1.1.0
      with:
        format: "YYYYMMDDHHmmss"
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.MYTOKEN }}
        file: build/ios/ipa/*.ipa
        tag: ${{ steps.date.outputs.time  }}
        overwrite: true
        file_glob: true
        
#     - name: Deploy
#       uses: crazy-max/ghaction-github-pages@v2
#       with:
#         target_branch: gh-pages
#         build_dir: dist
#         fqdn: clash.razord.top
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
